version: '3'
services:
    dfm-thesis:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                DFM_COMMIT: thesis/test
        environment:
            DFM_WEBSOCKET_PORT: 3200
            DFM_HTTP_PORT: 3201
            DFM_UPLOAD_LIMIT: 200
            DFM_PERSISTENT_DATA_PATH: "/dfm-data"
            DFM_ENABLE_SSL: "false"
            DFM_ENABLE_HSTS: "false"
            DFM_FORCE_NEW_SSL_CERTS: "false"
            DFM_USE_DB: "false"
        networks:
          - nh-dfm
    dfm-main:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                DFM_COMMIT: thesis/control
        ports:
            - "8002:80"
        environment:
            DFM_WEBSOCKET_PORT: 3200
            DFM_HTTP_PORT: 3201
            DFM_UPLOAD_LIMIT: 200
            DFM_PERSISTENT_DATA_PATH: "/dfm-data"
            DFM_ENABLE_SSL: "false"
            DFM_ENABLE_HSTS: "false"
            DFM_FORCE_NEW_SSL_CERTS: "false"
            DFM_USE_DB: "false"
        networks:
          - nh-dfm
    dfm-client-patients:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                DFM_COMMIT: thesis/client-ticks
        ports:
            - "8003:80"
        environment:
            DFM_WEBSOCKET_PORT: 3200
            DFM_HTTP_PORT: 3201
            DFM_UPLOAD_LIMIT: 200
            DFM_PERSISTENT_DATA_PATH: "/dfm-data"
            DFM_ENABLE_SSL: "false"
            DFM_ENABLE_HSTS: "false"
            DFM_FORCE_NEW_SSL_CERTS: "false"
            DFM_USE_DB: "false"
        networks:
          - nh-dfm
    dfm-benchmark:
        build:
            context: ..
            dockerfile: docker/benchmark.Dockerfile
        depends_on:
          - dfm-main
          - dfm-thesis
        volumes:
          - type: bind
            source: ./results/scenarios
            target: /usr/local/app/nh-thesis-benchmarks/scenarios
          - type: bind
            source: ./results/data
            target: /usr/local/app/nh-thesis-benchmarks/data
        networks:
          - nh-dfm
networks:
  nh-dfm:
