version: '3'
services:
    dfm-thesis:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                DFM_COMMIT: thesis/test
        restart: unless-stopped
        ports:
            - 8001:80
        environment:
            DFM_WEBSOCKET_PORT: 3200
            DFM_HTTP_PORT: 3201
            DFM_UPLOAD_LIMIT: 200
            DFM_PERSISTENT_DATA_PATH: "/dfm-data"
            DFM_ENABLE_SSL: "false"
            DFM_ENABLE_HSTS: "false"
            DFM_FORCE_NEW_SSL_CERTS: "false"
            DFM_USE_DB: "false"
    dfm-main:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                DFM_COMMIT: thesis/control
        restart: unless-stopped
        ports:
            - 8002:80
        environment:
            DFM_WEBSOCKET_PORT: 3200
            DFM_HTTP_PORT: 3201
            DFM_UPLOAD_LIMIT: 200
            DFM_PERSISTENT_DATA_PATH: "/dfm-data"
            DFM_ENABLE_SSL: "false"
            DFM_ENABLE_HSTS: "false"
            DFM_FORCE_NEW_SSL_CERTS: "false"
            DFM_USE_DB: "false"
