name: Create Release PRs

on:
    workflow_dispatch:
        inputs:
            versionName:
                description: 'Name of version  (i.e. 1.2.3)'
                required: true

jobs:
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Create release branch
              run: git checkout -b release/v${{ github.event.inputs.versionName }}
            - name: Initialize git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com
            - name: Update version in packages
              run: bash .github/update-version.sh "${{ github.event.inputs.versionName }}"
            - name: Update versions in package-locks
              run: npm run setup:package-lock-only
            - name: stage changes
              run: git add .
            - name: show changes
              run: git diff --staged
            - name: debug setup
              run: npm run setup:ci
            - name: show changes 2
              run: |
                git diff
                git diff --staged
            - name: Debug commit
              run: git commit --message "Debug v${{ github.event.inputs.versionName }}"
            - name: Push new branch
              run: git push origin release/v${{ github.event.inputs.versionName }}
            - name: Create pull request into main
              uses: thomaseizinger/create-pull-request@1.3.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  head: release/v${{ github.event.inputs.versionName }}
                  base: main
                  title: Release v${{ github.event.inputs.versionName }}
                  reviewers: ${{ github.event.issue.user.login }}
                  body: |
                      This PR was created in response to a running workflow.
                      I've updated the version name and changelog.
            - name: Create pull request into dev
              uses: thomaseizinger/create-pull-request@1.3.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  head: release/v${{ github.event.inputs.versionName }}
                  base: dev
                  title: Release v${{ github.event.inputs.versionName }} into dev
                  reviewers: ${{ github.event.issue.user.login }}
                  body: |
                      This PR was created in response to a running workflow.
                      I've updated the version name and changelog.

